language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
install:
  - npm install
  - mkdir node_modules_new
  - mkdir node_modules_new/grunt-drupal-tasks
  - for fn in *; do if [ "$fn" != "node_modules_new" ]; then mv $fn node_modules_new/grunt-drupal-tasks; fi; done
  - cp -r node_modules_new/grunt-drupal-tasks/example/* .
  - mv node_modules_new node_modules
  - npm install
  - npm install -g grunt-cli
script:
  - grunt
  - npm test
