language: php
php:
  - 5.3
install:
  - ./test/create_working_copy.sh
  - cd test/working_copy
  - npm install -g grunt-cli
  - npm install -g mocha
script:
  - export PATH=$PATH:`pwd`/bin
  - grunt
  - grunt drush:liteinstall
  - grunt drush:runserver &
  - grunt behat
  - mocha node_modules/grunt-drupal-tasks/test
