language: php
php: 5.6
before_install:
  - composer self-update
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - sed -i '/opcache.so/d' `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - sed -i '/apc.so/d' `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - phpenv config-rm xdebug.ini
  - php -i
install:
  - echo "Code checkout disk usage"; du -chs .; ls -lRa
  - ./test/create_working_copy.sh
  - cd test/working_copy
  - echo "Example working copy disk usage"; du -chs .
  - npm install -g grunt-cli
  - npm install -g mocha
script:
  - export PATH=$PATH:`pwd`/bin
  - grunt --timer
  - echo "Example fully built disk usage"; du -chs .
  - grunt drush:liteinstall --timer
  - grunt drush:runserver &
  - until curl -I -XGET -s http://127.0.0.1:8080/misc/drupal.js 2>/dev/null | egrep -q '^HTTP.*200'; do sleep 0.5; done
  - grunt test --timer
  - mocha node_modules/grunt-drupal-tasks/test
