language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
install:
  - mkdir node_modules
  - mkdir node_modules/grunt-drupal-tasks
  - for fn in *; do if [ "$fn" != "node_modules" ]; then mv $fn node_modules/grunt-drupal-tasks; fi; done
  - cp -r node_modules/grunt-drupal-tasks/example/* .
  - npm install
  - npm install -g grunt-cli
script:
  - grunt
  - npm test
